### PR TITLE
add dpm-solver support (much faster than plms)

### PR DESCRIPTION
**Pull request by LuChengTHU**
DPM-Solver (https://github.com/LuChengTHU/dpm-solver) is much faster than PLMS and DDIM, which can generate almost converged samples in only 20-25 steps.

Example images of the difference between DDIM, PLMS, and DPM-Solver can be found in: https://github.com/LuChengTHU/dpm-solver/tree/main/example_v2/stable-diffusion

### CODE REVIEW

**Comment by LuChengTHU** [comment]
An example command for sampling by DPM-Solver:

```
python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --dpm_solver --ddim_steps 25
```

**Comment by rromb** [comment]
This is great, thank you very much :+1:

**Review by rajbala — COMMENTED** [review]
I used the instructions to install the dependencies:

```
conda env create -f environment.yaml
conda activate ldm
```

But I get the following error when I try to run `python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse"`

```
[Traceback (most recent call last):
  File "scripts/txt2img.py", line 20, in <module>
    from ldm.models.diffusion.dpm_solver import DPMSolverSampler
  File "/home/opc/stable-diffusion/ldm/models/diffusion/dpm_solver/__init__.py", line 1, in <module>
    from .sampler import DPMSolverSampler
  File "/home/opc/stable-diffusion/ldm/models/diffusion/dpm_solver/sampler.py", line 5, in <module>
    from .solver import NoiseScheduleVP, model_wrapper, DPM_Solver
ModuleNotFoundError: No module named 'ldm.models.diffusion.dpm_solver.solver'
]
```

Any ideas as to what is happening?

**Comment by rromb** [comment]
should be fixed in 21f890f9da3cfbeaba8e2ac3c425ee9e998d5229

**Comment by rajbala** [comment]
It is fixed indeed!  :)

**Pull request merged**
